export const ActionType = {
    APPLY_LEAVE: 'APPLY_LEAVE',
    APPLY_LEAVE_CLEAR: 'APPLY_LEAVE_CLEAR',
    LEAVE_DATE_CHANGE: 'LEAVE_DATE_CHANGE',
    LEAVE_TYPE_CHANGE: 'LEAVE_TYPE_CHANGE',
    LEAVE_REASON_CHANGE: 'LEAVE_REASON_CHANGE',
    NEW_NOTIFICATION: 'NEW_NOTIFICATION',
    CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION',
    DISPLAY_NOTIFICATION: 'DISPLAY_NOTIFICATION'
}
